# Generated by Django 4.2.5 on 2025-04-22 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "commands",
                    models.TextField(help_text="每行一个命令", verbose_name="命令列表"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_templates",
                        to="devices.devicetype",
                        verbose_name="适用设备类型",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_templates",
                        to="devices.vendor",
                        verbose_name="适用厂商",
                    ),
                ),
            ],
            options={
                "verbose_name": "命令模板",
                "verbose_name_plural": "命令模板",
                "unique_together": {("name", "vendor", "device_type")},
            },
        ),
        migrations.CreateModel(
            name="InspectionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("once", "一次性"),
                            ("daily", "每天"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                        ],
                        default="once",
                        max_length=20,
                        verbose_name="调度类型",
                    ),
                ),
                ("scheduled_time", models.DateTimeField(verbose_name="计划执行时间")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "command_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_tasks",
                        to="inspections.commandtemplate",
                        verbose_name="命令模板",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        related_name="inspection_tasks",
                        to="devices.device",
                        verbose_name="巡检设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检任务",
                "verbose_name_plural": "巡检任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("warning", "警告"),
                            ("error", "错误"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("command", models.TextField(verbose_name="执行命令")),
                ("output", models.TextField(verbose_name="命令输出")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "execution_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_results",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="inspections.inspectiontask",
                        verbose_name="巡检任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检结果",
                "verbose_name_plural": "巡检结果",
                "ordering": ["-execution_time"],
            },
        ),
    ]
