# Generated by Django 4.2.5 on 2025-04-22 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("task", "任务报告"),
                            ("device", "设备报告"),
                            ("summary", "汇总报告"),
                        ],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        upload_to="report_templates/", verbose_name="模板文件"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告模板",
                "verbose_name_plural": "报告模板",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="报告名称")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("task", "任务报告"),
                            ("device", "设备报告"),
                            ("summary", "汇总报告"),
                        ],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("html", "HTML"), ("pdf", "PDF"), ("excel", "Excel")],
                        default="html",
                        max_length=20,
                        verbose_name="报告格式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="generating",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                        verbose_name="报告文件",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "inspection_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="inspections.inspectiontask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检报告",
                "verbose_name_plural": "巡检报告",
                "ordering": ["-created_at"],
            },
        ),
    ]
