# Generated by Django 4.2.5 on 2025-04-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类型名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备类型",
                "verbose_name_plural": "设备类型",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="厂商名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "厂商",
                "verbose_name_plural": "厂商",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                ("ip_address", models.CharField(max_length=50, verbose_name="IP地址")),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("ssh", "SSH"),
                            ("telnet", "Telnet"),
                            ("snmp", "SNMP"),
                        ],
                        default="ssh",
                        max_length=10,
                        verbose_name="连接协议",
                    ),
                ),
                ("port", models.IntegerField(default=22, verbose_name="端口")),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                ("password", models.CharField(max_length=100, verbose_name="密码")),
                (
                    "enable_password",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="启用密码"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("maintenance", "维护中"),
                            ("unknown", "未知"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="位置"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "last_inspection",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次巡检时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="devices.devicetype",
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="devices.vendor",
                        verbose_name="厂商",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "ordering": ["-created_at"],
            },
        ),
    ]
